name: pression
version: '0.1.0.0'
synopsis: Initial project template from stack
description: Please see README.md
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
github: githubuser/pression
library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - base >=4.7 && <5
  - directory
  - rex
  - array
  - trifecta
  - insert-ordered-containers
  - text
  - lens
  - tagged
  - MonadRandom
  - process
  - filepath
  - extra
  - typed-process
  - bytestring
  - conduit-combinators
  - binary-conduit
  - binary
  - conduit-extra
  - streaming-commons
  - network-multicast
  - network
  - disk-free-space
  - fmt
  - string-conv
  - time
  - lrucaching
executables:
  pression-qml:
    main: Qml.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - pression
    - hsqml
    - text
    - transformers >=0.5
  pression-random:
    main: Random.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - pression
tests:
  pression-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - pression
data-files:
- 'qml/*.qml'
